// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * NudmUEAU
 *
 * UDM UE Authentication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ueauthentication

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi"
	"github.com/omec-project/openapi/models"
	"github.com/omec-project/udm/logger"
	"github.com/omec-project/udm/producer"
	"github.com/omec-project/util/httpwrapper"
)

// ConfirmAuth - Create a new confirmation event
/*func HTTPConfirmAuth(c *gin.Context) {
	var authEvent models.AuthEvent
	// step 1: retrieve http request body
	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := models.ProblemDetails{
			Title:  "System failure",
			Status: http.StatusInternalServerError,
			Detail: err.Error(),
			Cause:  "SYSTEM_FAILURE",
		}
		logger.UeauLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	// step 2: convert requestBody to openapi models
	err = openapi.Deserialize(&authEvent, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.UeauLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, authEvent)
	req.Params["supi"] = c.Params.ByName("supi")

	rsp := producer.HandleConfirmAuthDataRequest(req)

	responseBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.UeauLog.Errorln(err)
		problemDetails := models.ProblemDetails{
			Status: http.StatusInternalServerError,
			Cause:  "SYSTEM_FAILURE",
			Detail: err.Error(),
		}
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody)
	}
}*/

func HTTPConfirmAuth(c *gin.Context) {
	logger.UeauLog.Warnln("--- RUNNING TEMPORARY HARDCODED HANDLER FOR HTTPConfirmAuth ---")

	// Manually create a dummy response body.
	dummyEvent := models.AuthEvent{
		Success:            true,
		AuthEventId:        "hardcoded-uuid-for-testing", // This field exists in your patched model
		NfInstanceId:       "d5ddcd4e-7ab8-4b22-9275-08b364c70749",
		AuthType:           models.AuthType__5_G_AKA,
		ServingNetworkName: "5G:mnc093.mcc208.3gppnetwork.org",
	}

	// Manually create the Location header URI.
	supi := c.Params.ByName("supi")
	locationURI := fmt.Sprintf("https://udm:29503/nudm-ueau/v1/%s/auth-events/%s", supi, dummyEvent.AuthEventId)
	
	logger.UeauLog.Infof("Hardcoded Test: Attempting to set Location header to: [%s]", locationURI)
	
	// Use raw Gin functions to set the header and send the response.
	// This completely bypasses the producer and the httpwrapper.
	c.Header("Location", locationURI)
	c.JSON(http.StatusCreated, dummyEvent)
	
	logger.UeauLog.Warnf("--- FINISHED TEMPORARY HARDCODED HANDLER. Final response headers sent by Gin: %+v", c.Writer.Header())
}
