// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * NudmUEAU
 *
 * UDM UE Authentication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ueauthentication

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
	"github.com/omec-project/udm/producer"
	"github.com/omec-project/util/httpwrapper"
	utilLogger "github.com/omec-project/util/logger"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := utilLogger.NewGinWithZap(logger.GinLog)
	AddService(router)
	return router
}

func genAuthDataHandlerFunc(c *gin.Context) {
	c.Params = append(c.Params, gin.Param{Key: "supiOrSuci", Value: c.Param("supi")})
	if strings.ToUpper("Post") == c.Request.Method {
		HttpGenerateAuthData(c)
		return
	}

	c.String(http.StatusNotFound, "404 page not found")
}

func AddService(engine *gin.Engine) *gin.RouterGroup {
	group := engine.Group("/nudm-ueau/v1")

	for _, route := range routes {
		switch route.Method {
		case "GET":
			group.GET(route.Pattern, route.HandlerFunc)
		case "POST":
			group.POST(route.Pattern, route.HandlerFunc)
		case "PUT":
			group.PUT(route.Pattern, route.HandlerFunc)
		case "DELETE":
			group.DELETE(route.Pattern, route.HandlerFunc)
		case "PATCH":
			group.PATCH(route.Pattern, route.HandlerFunc)
		}
	}

	genAuthDataPath := "/:supi/security-information/generate-auth-data"
	group.Any(genAuthDataPath, genAuthDataHandlerFunc)

	return group
}

func HTTPDeleteAuth(c *gin.Context) {
	supiParam := c.Params.ByName("supi")
	authEventIdParam := c.Params.ByName("authEventId")
	logger.UeauLog.Infof(">>>>> HTTP Inbound: Received PUT request for Auth Event deletion.")
	logger.UeauLog.Infof(">>>>> Path parameter supi: [%s]", supiParam)
	logger.UeauLog.Infof(">>>>> Path parameter authEventId: [%s]", authEventIdParam)

	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["supi"] = c.Params.ByName("supi")
	req.Params["authEventId"] = c.Params.ByName("authEventId")

	rsp := producer.HandleDeleteAuthRequest(req)

	logger.UeauLog.Infof("<<<<< HTTP Outbound: Sending response with status code: %d", rsp.Status)
	// A successful 204 response has no body.
	c.Status(rsp.Status)
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/",
		Index,
	},

	{
		"ConfirmAuth",
		strings.ToUpper("Post"),
		"/:supi/auth-events",
		HTTPConfirmAuth,
	},

	{
		"DeleteAuth",
		"PUT",
		"/:supi/auth-events/:authEventId",
		HTTPDeleteAuth,
	},
}
