// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package uecontextmanagement

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
	utilLogger "github.com/omec-project/util/logger"
)

const (
	pathAmf3gppAccess     = "/:ueId/registrations/amf-3gpp-access"
	pathAmfNon3gppAccess  = "/:ueId/registrations/amf-non-3gpp-access"
	pathSmsf3gppAccess    = "/:ueId/registrations/smsf-3gpp-access"
	pathSmsfNon3gppAccess = "/:ueId/registrations/smsf-non-3gpp-access"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := utilLogger.NewGinWithZap(logger.GinLog)
	AddService(router)
	return router
}

func AddService(engine *gin.Engine) *gin.RouterGroup {
	group := engine.Group("/nudm-uecm/v1")

	for _, route := range routes {
		switch route.Method {
		case "GET":
			group.GET(route.Pattern, route.HandlerFunc)
		case "POST":
			group.POST(route.Pattern, route.HandlerFunc)
		case "PUT":
			group.PUT(route.Pattern, route.HandlerFunc)
		case "DELETE":
			group.DELETE(route.Pattern, route.HandlerFunc)
		case "PATCH":
			group.PATCH(route.Pattern, route.HandlerFunc)
		}
	}

	return group
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/",
		Index,
	},

	{
		"GetAmf3gppAccess",
		strings.ToUpper("Get"),
		pathAmf3gppAccess,
		HTTPGetAmf3gppAccess,
	},

	{
		"GetAmfNon3gppAccess",
		strings.ToUpper("Get"),
		pathAmfNon3gppAccess,
		HTTPGetAmfNon3gppAccess,
	},

	{
		"RegistrationAmf3gppAccess",
		strings.ToUpper("Put"),
		pathAmf3gppAccess,
		HTTPRegistrationAmf3gppAccess,
	},

	{
		"Register",
		strings.ToUpper("Put"),
		pathAmfNon3gppAccess,
		HTTPRegistrationAmfNon3gppAccess,
	},

	{
		"UpdateAmf3gppAccess",
		strings.ToUpper("Patch"),
		pathAmf3gppAccess,
		HTTPUpdateAmf3gppAccess,
	},

	{
		"UpdateAmfNon3gppAccess",
		strings.ToUpper("Patch"),
		pathAmfNon3gppAccess,
		HTTPUpdateAmfNon3gppAccess,
	},

	{
		"DeregistrationSmfRegistrations",
		strings.ToUpper("Delete"),
		"/:ueId/registrations/smf-registrations/:pduSessionId",
		HTTPDeregistrationSmfRegistrations,
	},

	{
		"RegistrationSmfRegistrations",
		strings.ToUpper("Put"),
		"/:ueId/registrations/smf-registrations/:pduSessionId",
		HTTPRegistrationSmfRegistrations,
	},

	{
		"GetSmsf3gppAccess",
		strings.ToUpper("Get"),
		pathSmsf3gppAccess,
		HTTPGetSmsf3gppAccess,
	},

	{
		"DeregistrationSmsf3gppAccess",
		strings.ToUpper("Delete"),
		pathSmsf3gppAccess,
		HTTPDeregistrationSmsf3gppAccess,
	},

	{
		"DeregistrationSmsfNon3gppAccess",
		strings.ToUpper("Delete"),
		pathSmsfNon3gppAccess,
		HTTPDeregistrationSmsfNon3gppAccess,
	},

	{
		"GetSmsfNon3gppAccess",
		strings.ToUpper("Get"),
		pathSmsfNon3gppAccess,
		HTTPGetSmsfNon3gppAccess,
	},

	{
		"UpdateSMSFReg3GPP",
		strings.ToUpper("Put"),
		pathSmsf3gppAccess,
		HTTPUpdateSMSFReg3GPP,
	},

	{
		"RegistrationSmsfNon3gppAccess",
		strings.ToUpper("Put"),
		pathSmsfNon3gppAccess,
		HTTPRegistrationSmsfNon3gppAccess,
	},
}
